FROM registry.access.redhat.com/ubi8/ubi:8.0

LABEL Name="podmanremote-yum" \
    Vendor="com.garethahealy" \
    Maintainer="garethahealy (https://github.com/garethahealy/)" \
    Version="1.0" \
    License="Apache License, Version 2.0"

RUN yum install -y zip --setopt tsflags=nodocs